name: "CI/CD for Seira"
on:
  push:
  pull_request:

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v4
      - run: npm ci
      - run: npm run test
      - uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: JEST Tests
          path: junit.xml
          reporter: jest-junit
      - run: npm run build
      - uses: actions/upload-artifact@v4
        with:
          name: built-library
          path: dist

  release-tag:
    runs-on: ubuntu-latest
    if: startsWith(github.event.ref, 'refs/tags/')
    needs: unit-test
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v4
      - uses: actions/download-artifact@v4
        with:
          name: built-library
          path: dist
      - run: npm version $GITHUB_REF_NAME
      - run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
