name: "CI/CD for Seira"
on:
  push:
  pull_request:

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v4
      - run: npm ci
      - run: npm run test
      - uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: JEST Tests
          path: junit.xml
          reporter: jest-junit
      - run: npm run build
